GET http://localhost:3000/livros/

###
GET http://localhost:3000/livros/1

###

POST http://localhost:3000/livros/
Content-Type: application/json

{
    "titulo": "Portugol para iniciantes",
    "autor": "Jaden Smith"
}

###
PUT http://localhost:3000/livros/3
Content-Type: application/json

{
    "Titulo": "titulo teste",
    "autor": "autor teste"
}

###
DELETE http://localhost:3000/livros/3


